/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import database.DBConnect;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.ScrollPane;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.AbstractAction;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.event.ListSelectionListener;
import lmsschoolproject.Emprunt;
import lmsschoolproject.Etudiant;
import lmsschoolproject.Livre;
import lmsschoolproject.Utilisateur;

/**
 *
 * @author KIBITI Wen Life
 */
public class FenetreRetournerEmprunt extends javax.swing.JFrame {
    private Utilisateur utilisateur;
    private String typeUsager;
    private static JPopupMenu popup;
    /**
     * Creates new form FenetreRetournerEmprunt
     */
    public FenetreRetournerEmprunt() {
        initComponents(); 
        this.panel_Emprunts_NonRembourse.setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbbx_SelectionTypeUsager = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btn_verifier_Identifiant = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel_Emprunts_NonRembourse = new javax.swing.JPanel();
        btn_terminer_transaction = new javax.swing.JButton();
        txt_identifiant_usager = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TypeUsager");

        cbbx_SelectionTypeUsager.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etudiant", "Lecturer" }));

        jLabel2.setText("Identifiant");

        btn_verifier_Identifiant.setText("verifier");
        btn_verifier_Identifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verifier_IdentifiantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_Emprunts_NonRembourseLayout = new javax.swing.GroupLayout(panel_Emprunts_NonRembourse);
        panel_Emprunts_NonRembourse.setLayout(panel_Emprunts_NonRembourseLayout);
        panel_Emprunts_NonRembourseLayout.setHorizontalGroup(
            panel_Emprunts_NonRembourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        panel_Emprunts_NonRembourseLayout.setVerticalGroup(
            panel_Emprunts_NonRembourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel_Emprunts_NonRembourse);

        btn_terminer_transaction.setBackground(new java.awt.Color(0, 153, 0));
        btn_terminer_transaction.setText("Terminer");
        btn_terminer_transaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terminer_transactionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbx_SelectionTypeUsager, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_identifiant_usager))
                        .addGap(68, 68, 68)
                        .addComponent(btn_verifier_Identifiant)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_terminer_transaction)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_terminer_transaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbbx_SelectionTypeUsager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_identifiant_usager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_verifier_Identifiant))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verifier_IdentifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verifier_IdentifiantActionPerformed
        // TODO add your handling code here:
        String typeUsager = this.cbbx_SelectionTypeUsager.getSelectedItem().toString();
        String identifiantUsager = this.txt_identifiant_usager.getText();
        if(typeUsager.equals("Etudiant")){
            boolean validation = Etudiant.validerMatricule(identifiantUsager);
            if(validation){
                this.utilisateur = Etudiant.getEtudiant(identifiantUsager);
                this.typeUsager = typeUsager;
                 this.panel_Emprunts_NonRembourse.removeAll();
               
                JOptionPane.showMessageDialog(rootPane, "Identifiant valide");
                JList<Emprunt> emprunts = Etudiant.chercherEmpruntsEtudiant(identifiantUsager);
                
                emprunts.setSelectionBackground(Color.BLUE);
                emprunts.setBackground(Color.gray);
                
                emprunts.addListSelectionListener(createEmpruntSelectionListener(emprunts));
                
                
                if(emprunts.getModel().getSize() == 0){
                    System.out.println("no pending borrows");
                    this.panel_Emprunts_NonRembourse.add(new JLabel("          Aucun Emprunt non Rembourse"),BorderLayout.CENTER); 
                     this.panel_Emprunts_NonRembourse.setVisible(true);
                     this.panel_Emprunts_NonRembourse.revalidate();
                     this.panel_Emprunts_NonRembourse.repaint();
                    
                      
                }else{
                    System.out.println("Emprunts trouves");
                   
                    this.panel_Emprunts_NonRembourse.add(emprunts,BorderLayout.CENTER);
                   
                     this.panel_Emprunts_NonRembourse.setVisible(true);
                     this.panel_Emprunts_NonRembourse.revalidate();
                     this.panel_Emprunts_NonRembourse.repaint();
                }
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Identifiant INVALIDE");
            }
            
        }
    }//GEN-LAST:event_btn_verifier_IdentifiantActionPerformed

    private void btn_terminer_transactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terminer_transactionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_terminer_transactionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreRetournerEmprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreRetournerEmprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreRetournerEmprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreRetournerEmprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreRetournerEmprunt().setVisible(true);
            }
        });
    }
    
    private  ListSelectionListener createEmpruntSelectionListener(JList<Emprunt> list){
        return e -> {
          if (!e.getValueIsAdjusting()) {
              System.out.println(list.getSelectedValue());
              
              
        //instancier l'objet menu contextuel
       popup = new JPopupMenu();
        
        //ajouter des options au menu contextuel
        popup.add(new JMenuItem(new AbstractAction("retourner"){
                  @Override
                  public void actionPerformed(ActionEvent e) {
                      
                      int option = JOptionPane.showConfirmDialog(null,"Voulez vous confirmer le retour de cet Emprunt avec le paiement des penalites(si presentes)?");
                      if(option == 0){
                          Emprunt emprunt = list.getSelectedValue();
                          //emprunt.rembourserEmprunt();
                          miseAjour();
                      }
                  }
        }));
       
        
         popup.show(list,list.getMousePosition().x,list.getMousePosition().y);
          }
      };
    }
   
     private void miseAjour(){
       
         String typeUsager = this.cbbx_SelectionTypeUsager.getSelectedItem().toString();
        String identifiantUsager = this.txt_identifiant_usager.getText();
        if(typeUsager.equals("Etudiant")){
            boolean validation = Etudiant.validerMatricule(identifiantUsager);
            if(validation){
                this.utilisateur = Etudiant.getEtudiant(identifiantUsager);
                this.typeUsager = typeUsager;
                
               
                
                JList<Emprunt> emprunts = Etudiant.chercherEmpruntsEtudiant(identifiantUsager);
                if(emprunts.getModel().getSize() == 0){
                    System.out.println("no pending borrows");
                    this.panel_Emprunts_NonRembourse.removeAll();
                    this.panel_Emprunts_NonRembourse.add(new JLabel("          Aucun Emprunt non Rembourse"),BorderLayout.CENTER); 
                     this.panel_Emprunts_NonRembourse.setVisible(true);
                     this.panel_Emprunts_NonRembourse.revalidate();
                     this.panel_Emprunts_NonRembourse.repaint();
                  
                      
                }else{
                    System.out.println("Emprunts trouves");
                    
                    this.panel_Emprunts_NonRembourse.add(emprunts,BorderLayout.CENTER);
                     this.panel_Emprunts_NonRembourse.setVisible(true);
                     this.panel_Emprunts_NonRembourse.revalidate();
                     this.panel_Emprunts_NonRembourse.repaint();
                }
                
            }else{
                JOptionPane.showMessageDialog(rootPane, "Identifiant INVALIDE");
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_terminer_transaction;
    private javax.swing.JButton btn_verifier_Identifiant;
    private javax.swing.JComboBox<String> cbbx_SelectionTypeUsager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_Emprunts_NonRembourse;
    private javax.swing.JTextField txt_identifiant_usager;
    // End of variables declaration//GEN-END:variables
}
