/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;
import database.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lmsschoolproject.Etudiant;
/**
 *
 * @author KIBITI Wen Life
 */
public class FenetreInscrireUtilisateur extends javax.swing.JFrame {

    /**
     * Creates new form FenetreInscrireUtilisateur
     */
    public FenetreInscrireUtilisateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_matricule = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_prenom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_sexe = new javax.swing.JTextField();
        btn_CreerCompte = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_filiere = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_identifiantLT = new javax.swing.JTextField();
        txt_nameLT = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        txt_sexeLT = new javax.swing.JTextField();
        txt_departementLT = new javax.swing.JTextField();
        txt_telLT = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_emailTL = new javax.swing.JTextField();
        btn_enregistrerLT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_nameAD = new javax.swing.JTextField();
        txt_prenomAD = new javax.swing.JTextField();
        txt_confiemerAD = new javax.swing.JTextField();
        txt_emailAD = new javax.swing.JTextField();
        txt_telAD = new javax.swing.JTextField();
        txt_identifiantAD = new javax.swing.JTextField();
        txt_sexeAD = new javax.swing.JTextField();
        btn_enregistrerAD = new javax.swing.JButton();
        txtpasSwordAD = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("matricule");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 59, 77, -1));
        jPanel1.add(txt_matricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 56, 212, -1));

        jLabel2.setText("nom");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 102, -1, -1));
        jPanel1.add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 99, 212, -1));

        jLabel3.setText("prenom");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 145, -1, -1));
        jPanel1.add(txt_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 142, 212, -1));

        jLabel4.setText("sexe");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 195, -1, -1));
        jPanel1.add(txt_sexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 192, 212, -1));

        btn_CreerCompte.setText("Enregistrer");
        btn_CreerCompte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CreerCompteMouseClicked(evt);
            }
        });
        jPanel1.add(btn_CreerCompte, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 403, -1, -1));

        jLabel7.setText("filiere");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 244, -1, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 336, -1, -1));
        jPanel1.add(txt_filiere, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 238, 212, -1));

        jLabel5.setText("tel");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 286, -1, -1));

        jLabel6.setText("e_mail");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 343, -1, -1));
        jPanel1.add(txt_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 283, 212, -1));

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 337, 212, -1));

        jTabbedPane1.addTab("Etudiant", jPanel1);

        jLabel18.setText("identifiant");

        jLabel19.setText("nom");

        jLabel20.setText("prenom");

        jLabel21.setText("sexe");

        jLabel22.setText("departement");

        jLabel23.setText("tel");

        txt_nameLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameLTActionPerformed(evt);
            }
        });

        txt_departementLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_departementLTActionPerformed(evt);
            }
        });

        txt_telLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telLTActionPerformed(evt);
            }
        });

        jLabel24.setText("email");

        btn_enregistrerLT.setText("Enregistrer");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_identifiantLT)
                    .addComponent(txt_nameLT)
                    .addComponent(jTextField3)
                    .addComponent(txt_sexeLT)
                    .addComponent(txt_departementLT)
                    .addComponent(txt_telLT)
                    .addComponent(txt_emailTL, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addGap(520, 520, 520))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(btn_enregistrerLT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(txt_identifiantLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_nameLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addGap(55, 55, 55))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_sexeLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_departementLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(26, 26, 26)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(txt_emailTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btn_enregistrerLT)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lecturer", jPanel3);

        jLabel8.setText("nom");

        jLabel10.setText("prenom");

        jLabel11.setText("sexe");

        jLabel12.setText("identifiant");

        jLabel13.setText("tel");

        jLabel14.setText("email");

        jLabel15.setText("password");

        jLabel16.setText("confirmer password");

        txt_confiemerAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_confiemerADActionPerformed(evt);
            }
        });

        btn_enregistrerAD.setText("Enregistrer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_confiemerAD)
                    .addComponent(txt_emailAD)
                    .addComponent(txt_telAD)
                    .addComponent(txt_identifiantAD)
                    .addComponent(txt_prenomAD)
                    .addComponent(txt_sexeAD)
                    .addComponent(txt_nameAD)
                    .addComponent(txtpasSwordAD, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addGap(572, 572, 572))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btn_enregistrerAD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(txt_nameAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_prenomAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_sexeAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12))
                    .addComponent(txt_identifiantAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_emailAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(txtpasSwordAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(txt_confiemerAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btn_enregistrerAD)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Administrateur", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CreerCompteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CreerCompteMouseClicked
        // TODO add your handling code here:
        String matricule = this.txt_matricule.getText();
        String nom = this.txt_nom.getText();
        String prenom = this.txt_prenom.getText();
        String sexe = this.txt_sexe.getText();
        String filiere = this.txt_filiere.getText();
        String numtel = this.txt_tel.getText();
        String email = this.txt_email.getText();
       
        
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Date date = null;
         java.sql.Date sqldate = null;
        try {
            date = sdf.parse(sdf.format(new Date()));
            sqldate = new java.sql.Date(date.getTime());
        } catch (ParseException ex) {
            Logger.getLogger(FenetreInscrireUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        Etudiant etudiantInscris = new Etudiant(matricule,nom,prenom,sexe,filiere,numtel,email,date);
             try{
                 Connection con = DBConnect.connect();
                 String insertQuery = "INSERT INTO `etudiant`(`nom`, `prenom`, `sexe`, `Filiere`, `dateInscription`, `matricule`,`telephone`,`email`) VALUES (?,?,?,?,?,?,?,?)";
                 
                PreparedStatement requeteInsertion = con.prepareStatement(insertQuery);
                requeteInsertion.setString(1,nom);
                requeteInsertion.setString(2,prenom);
                requeteInsertion.setString(3, sexe);
                requeteInsertion.setString(4,filiere);
                requeteInsertion.setDate(5,sqldate);
                requeteInsertion.setString(6,matricule);
                requeteInsertion.setString(7,numtel);
                requeteInsertion.setString(8, email);
                      
                requeteInsertion.execute();
                JOptionPane.showMessageDialog(null, "Enregistree avec success");
            
                con.close();
                
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null, "Erreur Enregistrement");
                System.out.println(e);
            }
          
        
       
        
        
        
        
    }//GEN-LAST:event_btn_CreerCompteMouseClicked

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_nameLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameLTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameLTActionPerformed

    private void txt_departementLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_departementLTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_departementLTActionPerformed

    private void txt_telLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telLTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telLTActionPerformed

    private void txt_confiemerADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_confiemerADActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_confiemerADActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreInscrireUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreInscrireUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreInscrireUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreInscrireUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreInscrireUtilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CreerCompte;
    private javax.swing.JButton btn_enregistrerAD;
    private javax.swing.JButton btn_enregistrerLT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txt_confiemerAD;
    private javax.swing.JTextField txt_departementLT;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_emailAD;
    private javax.swing.JTextField txt_emailTL;
    private javax.swing.JTextField txt_filiere;
    private javax.swing.JTextField txt_identifiantAD;
    private javax.swing.JTextField txt_identifiantLT;
    private javax.swing.JTextField txt_matricule;
    private javax.swing.JTextField txt_nameAD;
    private javax.swing.JTextField txt_nameLT;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JTextField txt_prenomAD;
    private javax.swing.JTextField txt_sexe;
    private javax.swing.JTextField txt_sexeAD;
    private javax.swing.JTextField txt_sexeLT;
    private javax.swing.JTextField txt_tel;
    private javax.swing.JTextField txt_telAD;
    private javax.swing.JTextField txt_telLT;
    private javax.swing.JPasswordField txtpasSwordAD;
    // End of variables declaration//GEN-END:variables
}
