/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lmsschoolproject.Administrateur;
import lmsschoolproject.PROJECTCONSTANTS;


/**
 *
 * @author KIBITI Wen Life
 */
public class FenetreModifierAdmin extends javax.swing.JFrame {
    Administrateur administrator;
    private FenetreAcceuil mFenetreAcceuil;
    /**
     * Creates new form FenetreModifierAdmin
     */
    public FenetreModifierAdmin(Administrateur admin,FenetreAcceuil acceuil) {
        initComponents();
        this.mFenetreAcceuil = acceuil;
        this.administrator = admin;
        this.lbl_name.setText(admin.getNom());
        this.lbl_prenom.setText(admin.getPrenom());
        if(admin.getSexe().equalsIgnoreCase("m")){
                    this.cbbx_sexe.setSelectedIndex(0);
                }else{
                    this.cbbx_sexe.setSelectedIndex(1);
                }
        this.lbl_email.setText(admin.getEmail());
        this.lbl_telephone.setText(admin.getNumTelephone());
        this.date_Inscription.setDate(admin.getDateInscription());
        this.lbl_motDePasse.setText(admin.getPassword());
        this.lbl_identifiant.setText(admin.getIdentifiant());
        
        String path = PROJECTCONSTANTS.IMAGES_PATH;
               String nomImageMasculin = "avatar_profil_masculin.png";
               String nomImageFeminine = "avatar_profil_feminin.png";

               //tout ceci pour redimensioner l'image
               BufferedImage img = null;
                try {
                    if(admin.getSexe().equalsIgnoreCase("m")){
                         img = ImageIO.read(new File(path+nomImageMasculin));
                    }else{
                         img = ImageIO.read(new File(path+nomImageFeminine));
                    }

                    Image dimg = img.getScaledInstance(100,100,Image.SCALE_SMOOTH);
                    ImageIcon imageIcon = new ImageIcon(dimg);
                    this.lbl_image.setIcon(imageIcon);
                    this.lbl_image.setText("");
                } catch (IOException exc) {
                    exc.printStackTrace();
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new GradientJPanel();
        lbl_image = new javax.swing.JLabel();
        btn_retour = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_prenom = new javax.swing.JLabel();
        date_Inscription = new com.toedter.calendar.JDateChooser();
        lbl_motDePasse = new javax.swing.JLabel();
        lbl_telephone = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        btn_modifier_nom = new javax.swing.JButton();
        btn_modifier_prenom = new javax.swing.JButton();
        btn_modifier_motDePasse = new javax.swing.JButton();
        btn_modifier_Telephone = new javax.swing.JButton();
        btn_modifierEmail = new javax.swing.JButton();
        btn_mettreAJour = new javax.swing.JButton();
        cbbx_sexe = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lbl_identifiant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_image.setText("jLabel1");

        btn_retour.setText("retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom");

        jLabel3.setText("Prenom");

        jLabel4.setText("Sexe");

        jLabel5.setText("DateInscription");

        jLabel6.setText("MotDePasse");

        jLabel7.setText("Telephone ");

        jLabel8.setText("Email");

        lbl_name.setText("jLabel9");

        lbl_prenom.setText("fs");

        lbl_motDePasse.setText("jLabel9");

        lbl_telephone.setText("jLabel9");

        lbl_email.setText("jLabel9");

        btn_modifier_nom.setText("modifier");
        btn_modifier_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_nomActionPerformed(evt);
            }
        });

        btn_modifier_prenom.setText("modifier");
        btn_modifier_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_prenomActionPerformed(evt);
            }
        });

        btn_modifier_motDePasse.setText("modifier");
        btn_modifier_motDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_motDePasseActionPerformed(evt);
            }
        });

        btn_modifier_Telephone.setText("modifier");
        btn_modifier_Telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_TelephoneActionPerformed(evt);
            }
        });

        btn_modifierEmail.setText("modifier");
        btn_modifierEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierEmailActionPerformed(evt);
            }
        });

        btn_mettreAJour.setText("mettre a jour");
        btn_mettreAJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mettreAJourActionPerformed(evt);
            }
        });

        cbbx_sexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel1.setText("identifiant");

        lbl_identifiant.setText("id");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btn_retour)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(date_Inscription, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_modifierEmail))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_telephone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(lbl_motDePasse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_modifier_motDePasse, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_modifier_Telephone, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(lbl_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_modifier_prenom))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(btn_modifier_nom))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_identifiant, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbx_sexe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_mettreAJour)
                .addGap(223, 223, 223))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_retour)
                .addGap(9, 9, 9)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modifier_nom))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addComponent(lbl_identifiant)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modifier_prenom))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbx_sexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_Inscription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_motDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modifier_motDePasse))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modifier_Telephone))
                        .addGap(31, 31, 31)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modifierEmail))))
                .addGap(75, 75, 75)
                .addComponent(btn_mettreAJour)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mettreAJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mettreAJourActionPerformed
        // TODO add your handling code here:
        Administrateur n;
            String nom = this.lbl_name.getText();
            String prenom = this.lbl_prenom.getText();
            String sexe = this.cbbx_sexe.getSelectedItem().toString();
            String tel = this.lbl_telephone.getText();
            String email = this.lbl_email.getText();
            String mdp = this.lbl_motDePasse.getText();

            n = new Administrateur(null,nom,prenom,sexe,tel,email,mdp,null);
        
            if(Administrateur.updateAdmin(administrator, n)){
                JOptionPane.showMessageDialog(rootPane, "Modifications  Enregistree avec success");
                this.dispose();
            }else{
                 JOptionPane.showMessageDialog(null, "Erreur d'execution verifier puis reessayer a nouveau ");
            }
    }//GEN-LAST:event_btn_mettreAJourActionPerformed

    private void btn_modifier_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_nomActionPerformed
        // TODO add your handling code here:
        String nouveau_titre = JOptionPane.showInputDialog("Entrez Le nouveau nom");
        if(nouveau_titre != null){
            if(nouveau_titre.length() > 0){
                this.lbl_name.setText(nouveau_titre);
            }
        }
    }//GEN-LAST:event_btn_modifier_nomActionPerformed

    private void btn_modifier_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_prenomActionPerformed
        // TODO add your handling code here:
        String nouveau_titre = JOptionPane.showInputDialog("Entrez Le nouveau prenom");
        if(nouveau_titre != null){
            if(nouveau_titre.length() > 0){
                this.lbl_prenom.setText(nouveau_titre);
            }
        }
    }//GEN-LAST:event_btn_modifier_prenomActionPerformed

    private void btn_modifier_motDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_motDePasseActionPerformed
        // TODO add your handling code here:
        String nouveau_titre = JOptionPane.showInputDialog("Entrez Le nouveau nom de l'Etudiant");
        if(nouveau_titre != null){
            if(nouveau_titre.length() > 0){
                this.lbl_motDePasse.setText(nouveau_titre);
            }
        }
    }//GEN-LAST:event_btn_modifier_motDePasseActionPerformed

    private void btn_modifier_TelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_TelephoneActionPerformed
        // TODO add your handling code here:
        String nouveau_titre = JOptionPane.showInputDialog("Entrez Le nouveau numero de telephone");
        if(nouveau_titre != null){
            if(nouveau_titre.length() > 0){
                this.lbl_telephone.setText(nouveau_titre);
            }
        }
    }//GEN-LAST:event_btn_modifier_TelephoneActionPerformed

    private void btn_modifierEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierEmailActionPerformed
        // TODO add your handling code here:
        String nouveau_titre = JOptionPane.showInputDialog("Entrez Le nouveel Email");
        if(nouveau_titre != null){
            if(nouveau_titre.length() > 0){
                this.lbl_email.setText(nouveau_titre);
            }
        }
    }//GEN-LAST:event_btn_modifierEmailActionPerformed

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed
        // TODO add your handling code here:
        this.mFenetreAcceuil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_retourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreModifierAdmin(null,null).setVisible(true);
            }
        });
    }
    
     protected class GradientJPanel extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g; 
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            
            GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0,0,width,height);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mettreAJour;
    private javax.swing.JButton btn_modifierEmail;
    private javax.swing.JButton btn_modifier_Telephone;
    private javax.swing.JButton btn_modifier_motDePasse;
    private javax.swing.JButton btn_modifier_nom;
    private javax.swing.JButton btn_modifier_prenom;
    private javax.swing.JButton btn_retour;
    private javax.swing.JComboBox<String> cbbx_sexe;
    private com.toedter.calendar.JDateChooser date_Inscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_identifiant;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_motDePasse;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_prenom;
    private javax.swing.JLabel lbl_telephone;
    // End of variables declaration//GEN-END:variables
}
