/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import database.DBConnect;
import java.awt.Image;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import utilities.ImageFilter;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author KIBITI Wen Life
 */
public class FenetreAjouterRessources extends javax.swing.JFrame {

    /**
     * Creates new form ajouter_resources
     */
    public FenetreAjouterRessources() {
        initComponents();
        //this.txt_datePublication.setDateFormatString("dd/MM/YYYY");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_titrelivre = new javax.swing.JTextField();
        txt_auteur = new javax.swing.JTextField();
        txt_nombredexemplaire = new javax.swing.JTextField();
        txt_positionement = new javax.swing.JTextField();
        txt_maisonedition = new javax.swing.JTextField();
        txt_categorie = new javax.swing.JTextField();
        txt_nbpage = new javax.swing.JTextField();
        txt_edition = new javax.swing.JTextField();
        btn_enregistrer = new javax.swing.JButton();
        btn_reinitialiser = new javax.swing.JButton();
        btn_importerImage = new javax.swing.JButton();
        lbl_file_name = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_titreCD = new javax.swing.JTextField();
        txt_auteurCD = new javax.swing.JTextField();
        txt_nombreDexeemplaireCD = new javax.swing.JTextField();
        txt_positionementCD = new javax.swing.JTextField();
        txt_MaisonEditionCD = new javax.swing.JTextField();
        txt_dureeCD = new javax.swing.JTextField();
        txt_tailleCD = new javax.swing.JTextField();
        bouton_connexion2 = new javax.swing.JButton();
        bouton_connexion5 = new javax.swing.JButton();
        importer_image = new javax.swing.JLabel();
        txt_importerCD = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_auteurRSD = new javax.swing.JTextField();
        txt_titreRSD = new javax.swing.JTextField();
        txt_nombreexemplaireRSD = new javax.swing.JTextField();
        txt_positionnementRSD = new javax.swing.JTextField();
        txt_maisonEditionRSD = new javax.swing.JTextField();
        bouton_connexion3 = new javax.swing.JButton();
        bouton_reinitialiser = new javax.swing.JButton();
        importerImageMDR = new javax.swing.JButton();
        importer_Imgageici = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titre");

        jLabel2.setText("Auteur");

        jLabel3.setText("DatePublication");

        jLabel4.setText("NombreDexemplaire");

        jLabel5.setText("positionnement");

        jLabel6.setText("MaisonEdition");

        jLabel7.setText("Style_cathegorie");

        jLabel8.setText("nbPges");

        jLabel9.setText("Edition");

        txt_maisonedition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maisoneditionActionPerformed(evt);
            }
        });

        txt_categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_categorieActionPerformed(evt);
            }
        });

        txt_nbpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nbpageActionPerformed(evt);
            }
        });

        btn_enregistrer.setText("enregistrer");
        btn_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerActionPerformed(evt);
            }
        });

        btn_reinitialiser.setText("reitianiliser");
        btn_reinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reinitialiserActionPerformed(evt);
            }
        });

        btn_importerImage.setText("importer image");
        btn_importerImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importerImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btn_importerImage)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_titrelivre, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txt_auteur)
                            .addComponent(txt_nombredexemplaire)
                            .addComponent(txt_positionement)
                            .addComponent(txt_maisonedition)
                            .addComponent(txt_categorie)
                            .addComponent(txt_nbpage)
                            .addComponent(txt_edition))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_file_name, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btn_reinitialiser)
                        .addGap(90, 90, 90)
                        .addComponent(btn_enregistrer)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_titrelivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_auteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_nombredexemplaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_positionement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_maisonedition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_nbpage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_file_name, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_importerImage)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_enregistrer)
                            .addComponent(btn_reinitialiser))
                        .addGap(17, 17, 17))))
        );

        jTabbedPane1.addTab("nouveaux_livres", jPanel1);

        jLabel10.setText("Auteur");

        jLabel11.setText("DatePublication");

        jLabel12.setText("NombreDexemplaire");

        jLabel13.setText("Positionemnt");

        jLabel14.setText("MaisonEdition");

        jLabel15.setText("Dureé");

        jLabel16.setText("Taille");

        jLabel17.setText("Titre");

        bouton_connexion2.setText("reitianiliser");
        bouton_connexion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_connexion2ActionPerformed(evt);
            }
        });

        bouton_connexion5.setText("enregistrer");
        bouton_connexion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_connexion5ActionPerformed(evt);
            }
        });

        txt_importerCD.setText("importer_image");
        txt_importerCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_importerCDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_auteurCD, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txt_titreCD, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txt_nombreDexeemplaireCD, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txt_positionementCD, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txt_MaisonEditionCD, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txt_dureeCD, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txt_tailleCD, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_importerCD)
                        .addGap(18, 18, 18)
                        .addComponent(bouton_connexion5)
                        .addGap(45, 45, 45)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bouton_connexion2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                        .addComponent(importer_image, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(txt_titreCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jLabel10))
                    .addComponent(txt_auteurCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel11)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_nombreDexeemplaireCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(importer_image, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_positionementCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_MaisonEditionCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_dureeCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txt_tailleCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton_connexion5)
                    .addComponent(bouton_connexion2)
                    .addComponent(txt_importerCD))
                .addGap(27, 27, 27))
        );

        jTabbedPane1.addTab("nouveaux_CD", jPanel2);

        jLabel18.setText("Titre");

        jLabel19.setText("Auteur");

        jLabel20.setText("DatePublication");

        jLabel21.setText("NombreDexemplaire");

        jLabel22.setText("Positionement");

        jLabel23.setText("MasonEdition");

        bouton_connexion3.setText("enregistrer");
        bouton_connexion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_connexion3ActionPerformed(evt);
            }
        });

        bouton_reinitialiser.setText("reitianiliser");
        bouton_reinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_reinitialiserActionPerformed(evt);
            }
        });

        importerImageMDR.setText("importerImage");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)))
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txt_titreRSD, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_auteurRSD, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(txt_nombreexemplaireRSD, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(txt_positionnementRSD, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(txt_maisonEditionRSD, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                        .addGap(192, 192, 192)
                        .addComponent(importer_Imgageici, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(importerImageMDR)
                        .addGap(55, 55, 55)
                        .addComponent(bouton_connexion3)))
                .addContainerGap(344, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(351, 351, 351)
                    .addComponent(bouton_reinitialiser)
                    .addContainerGap(638, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_titreRSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(importer_Imgageici, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(txt_auteurRSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addComponent(jLabel20)
                        .addGap(52, 52, 52)))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_nombreexemplaireRSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(txt_positionnementRSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(txt_maisonEditionRSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouton_connexion3)
                    .addComponent(importerImageMDR))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(553, Short.MAX_VALUE)
                    .addComponent(bouton_reinitialiser)
                    .addGap(5, 5, 5)))
        );

        jTabbedPane1.addTab("materielderecherche", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nbpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nbpageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nbpageActionPerformed

    private void txt_categorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_categorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_categorieActionPerformed

    private void txt_maisoneditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maisoneditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maisoneditionActionPerformed

    private void btn_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerActionPerformed
            // TODO add your handling code here:
           
            String titre = txt_titrelivre.getText();
            String auteur = txt_auteur.getText();
            int nbExemplaire = Integer.parseInt(txt_nombredexemplaire.getText());
            String position = txt_positionement.getText();
            String categorie = txt_categorie.getText();
            String edition = txt_edition.getText();
            String maison_edition = txt_maisonedition.getText();
            int nbPages = Integer.parseInt(txt_nbpage.getText());
            String nomImage = lbl_file_name.getText();
          
            
            
           java.util.Date d = null;//txt_datePublication.getDate();
           java.sql.Date sqldate = null;
            if (d == null) {
                System.out.println("No date specified!");
            } else {
                sqldate = new java.sql.Date(d.getTime());
                // Do something with sqldate
            }
            
           
           
            
            
            
            
             
          
        try{
                  Connection con = DBConnect.connect();
                 String insertQuery = "INSERT INTO `livre`(`Titre`, `Auteur`, `DatePublication`, `NombreDexemplaires`, `Positionement`, `MaisonEdition`, `Stylecategorie`, `nbPage`, `edition`,`nomImage`) VALUES (?,?,?,?,?,?,?,?,?,?)";
                 
                PreparedStatement requeteInsertion = con.prepareStatement(insertQuery);
                requeteInsertion.setString(1,titre);
                 requeteInsertion.setString(2,auteur);
                  requeteInsertion.setDate(3, sqldate);
                  requeteInsertion.setInt(4, nbExemplaire);
                   requeteInsertion.setString(5,position);
                    requeteInsertion.setString(6,maison_edition);
                     requeteInsertion.setString(7,categorie);
                      requeteInsertion.setInt(8,nbPages);
                      requeteInsertion.setString(9,edition);
                      requeteInsertion.setString(10,nomImage);
                      
                requeteInsertion.execute();
                JOptionPane.showMessageDialog(null, "Enregistree avec success");
            
                con.close();
                
        }catch(Exception e){ 
            System.out.println(e);
        }
        
        

    }//GEN-LAST:event_btn_enregistrerActionPerformed

    private void btn_reinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reinitialiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reinitialiserActionPerformed

    private void bouton_connexion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_connexion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_connexion2ActionPerformed

    private void bouton_connexion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_connexion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_connexion3ActionPerformed

    private void bouton_reinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_reinitialiserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_reinitialiserActionPerformed

    private void bouton_connexion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_connexion5ActionPerformed

// pour le cd ici sera mis le code d'execution


     String titre = txt_titreCD.getText();
            String auteur = txt_auteurCD.getText();
            int nbExemplaire = Integer.parseInt(txt_nombreDexeemplaireCD.getText());
            String position = txt_positionementCD.getText();
            String maison_edition = txt_MaisonEditionCD.getText();
            int taille=Integer.parseInt(txt_tailleCD.getText());
            String duree=txt_dureeCD.getText();
            String nomImage = importer_image.getText();
          
            
            
           java.util.Date d = null;//txt_datedepublicationCD.getDate();
           java.sql.Date sqldate = null;
            if (d == null) {
                System.out.println("No date specified!");
            } else {
                sqldate = new java.sql.Date(d.getTime());
                // Do something with sqldate
            }
            
           
           
            
            
            
            
             
          
        try{
                  Connection con = DBConnect.connect();
                 String insertQuery = "INSERT INTO `CD`(`Titre`, `Auteur`, `DatePublication`, `NombreDexemplaires`, `Positionement`, `MaisonEdition`, `duree`, `taille`,`nomImage`) VALUES (?,?,?,?,?,?,?,?,?)";
                 
                PreparedStatement requeteInsertion = con.prepareStatement(insertQuery);
                requeteInsertion.setString(1,titre);
                 requeteInsertion.setString(2,auteur);
                  requeteInsertion.setDate(3, sqldate);
                  requeteInsertion.setInt(4, nbExemplaire);
                   requeteInsertion.setString(5,position);
                    requeteInsertion.setString(6,maison_edition);
                      requeteInsertion.setString(7,duree);
                       requeteInsertion.setInt(8,taille);
                      requeteInsertion.setString(9,nomImage);
                      
                requeteInsertion.execute();
                JOptionPane.showMessageDialog(null, "Enregistree avec success");
            
                con.close();
        }catch(Exception e){
            System.out.println(e);
        }





        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_connexion5ActionPerformed

    private void btn_importerImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importerImageActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new ImageFilter());
        fileChooser.setAcceptAllFileFilterUsed(false);
        
        int option = fileChooser.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            lbl_file_name.setText(file.getName());
            
            try{
                RenderedImage image = ImageIO.read(file);
                ImageIO.write(image,"jpg",new File("C:\\Users\\KIBITI Wen Life\\Documents\\NetBeansProjects\\LMSSchoolProject\\build\\images\\"+file.getName()));
                lbl_file_name.setIcon(new ImageIcon("C:\\Users\\KIBITI Wen Life\\Documents\\NetBeansProjects\\LMSSchoolProject\\build\\images\\"+file.getName()));
            }catch(IOException e){
                System.out.println(e);
            }
        }else{
             lbl_file_name.setText(" Aucune Image Choisie  ");
        }
    }//GEN-LAST:event_btn_importerImageActionPerformed

    private void txt_importerCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_importerCDActionPerformed

// pour importer l'image
  JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new ImageFilter());
        fileChooser.setAcceptAllFileFilterUsed(false);
        
        int option = fileChooser.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            importer_image.setText(file.getName());
            
            try{
                RenderedImage image = ImageIO.read(file);
                ImageIO.write(image,"jpg",new File("C:\\Users\\KIBITI Wen Life\\Documents\\NetBeansProjects\\LMSSchoolProject\\build\\images\\"+file.getName()));
                importer_image.setIcon(new ImageIcon("C:\\Users\\KIBITI Wen Life\\Documents\\NetBeansProjects\\LMSSchoolProject\\build\\images\\"+file.getName()));
            }catch(IOException e){
                System.out.println(e);
            }
        }else{
             importer_image.setText(" Aucune Image Choisie  ");
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_txt_importerCDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreAjouterRessources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreAjouterRessources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreAjouterRessources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreAjouterRessources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreAjouterRessources().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_connexion2;
    private javax.swing.JButton bouton_connexion3;
    private javax.swing.JButton bouton_connexion5;
    private javax.swing.JButton bouton_reinitialiser;
    private javax.swing.JButton btn_enregistrer;
    private javax.swing.JButton btn_importerImage;
    private javax.swing.JButton btn_reinitialiser;
    private javax.swing.JButton importerImageMDR;
    private javax.swing.JLabel importer_Imgageici;
    private javax.swing.JLabel importer_image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_file_name;
    private javax.swing.JTextField txt_MaisonEditionCD;
    private javax.swing.JTextField txt_auteur;
    private javax.swing.JTextField txt_auteurCD;
    private javax.swing.JTextField txt_auteurRSD;
    private javax.swing.JTextField txt_categorie;
    private javax.swing.JTextField txt_dureeCD;
    private javax.swing.JTextField txt_edition;
    private javax.swing.JButton txt_importerCD;
    private javax.swing.JTextField txt_maisonEditionRSD;
    private javax.swing.JTextField txt_maisonedition;
    private javax.swing.JTextField txt_nbpage;
    private javax.swing.JTextField txt_nombreDexeemplaireCD;
    private javax.swing.JTextField txt_nombredexemplaire;
    private javax.swing.JTextField txt_nombreexemplaireRSD;
    private javax.swing.JTextField txt_positionement;
    private javax.swing.JTextField txt_positionementCD;
    private javax.swing.JTextField txt_positionnementRSD;
    private javax.swing.JTextField txt_tailleCD;
    private javax.swing.JTextField txt_titreCD;
    private javax.swing.JTextField txt_titreRSD;
    private javax.swing.JTextField txt_titrelivre;
    // End of variables declaration//GEN-END:variables
}
