/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import database.DBConnect;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lmsschoolproject.Livre;
import lmsschoolproject.PROJECTCONSTANTS;
import utilities.ImageFilter;

/**
 *
 * @author KIBITI Wen Life
 */
public class FenetreModifierLivre extends javax.swing.JFrame {
    private Livre mLivre;
    private String newImageName;
     static final String path = PROJECTCONSTANTS.IMAGES_PATH;
     private FenetreAcceuil mFenetreAcceuil;

    /**
     * Creates new form FenetreModifierLivre
     */
    public FenetreModifierLivre(Livre livre,FenetreAcceuil acceuil) {
        initComponents();
        this.mFenetreAcceuil=  acceuil;
         String pathIcone = path+PROJECTCONSTANTS.IMAGE_ACCEUIL;
      
       //tout ceci pour redimensioner l'image
       BufferedImage imag = null;
        try {
            imag = ImageIO.read(new File(pathIcone));
            Image dimg = imag.getScaledInstance(50,50,Image.SCALE_SMOOTH);
            ImageIcon imageIcon = new ImageIcon(dimg);
            this.btn_retour.setIcon(imageIcon);
        } catch (IOException e) {
            e.printStackTrace();
        }
        this.mLivre = livre;
        if(livre != null){
            this.lbl_titre_livre.setText(livre.titre);
            this.lbl_auteur_livre.setText(livre.auteur);
            this.datechooser_ModifierDatePublication.setDate(livre.datePublication);
            this.lbl_categorie.setText(livre.categorie);
            this.lbl_edition.setText(livre.edition);
            this.lbl_nbPages.setText(String.valueOf(livre.nbPages));
            this.lbl_positionement.setText(livre.positionement);
            this.lbl_nb_exemplaire.setText(String.valueOf(livre.nbExemplaires));
            this.lbl_maison_edition.setText(livre.maisonEdition);
           
            this.newImageName = livre.nomImage;
            //tout ceci pour redimensioner l'image
            BufferedImage img = null;
             try {
                 img = ImageIO.read(new File(path+livre.nomImage));
                 Image dimg = img.getScaledInstance(this.lbl_image.getWidth(),this.lbl_image.getHeight(),Image.SCALE_SMOOTH);
                 ImageIcon imageIcon = new ImageIcon(dimg);
                 this.lbl_image.setIcon(imageIcon);
             } catch (IOException e) {
                 e.printStackTrace();
             }
             }
    }
     protected class GradientJPanel extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g; 
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            
            GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0,0,width,height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new GradientJPanel();
        lbl_image = new javax.swing.JLabel();
        btn_changer_image = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_titre_livre = new javax.swing.JLabel();
        lbl_auteur_livre = new javax.swing.JLabel();
        lbl_nb_exemplaire = new javax.swing.JLabel();
        datechooser_ModifierDatePublication = new com.toedter.calendar.JDateChooser();
        lbl_maison_edition = new javax.swing.JLabel();
        lbl_categorie = new javax.swing.JLabel();
        lbl_nbPages = new javax.swing.JLabel();
        lbl_edition = new javax.swing.JLabel();
        lbl_positionement = new javax.swing.JLabel();
        btn_MettreLivreAJour = new javax.swing.JButton();
        btn_modifierAuteur = new javax.swing.JButton();
        btn_modifier_nom = new javax.swing.JButton();
        btn_modifierNbExemplaire = new javax.swing.JButton();
        btn_changerMaisonEdition = new javax.swing.JButton();
        btn_ModiferCategorie = new javax.swing.JButton();
        btn_ModifierNbPages = new javax.swing.JButton();
        btn_ModifierEditionLivre = new javax.swing.JButton();
        btn_ModifierPositionement = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_changer_image.setText("changer Image");
        btn_changer_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_changer_imageMouseClicked(evt);
            }
        });
        btn_changer_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changer_imageActionPerformed(evt);
            }
        });

        jLabel2.setText("Titre");

        jLabel3.setText("Auteur");

        jLabel4.setText("Date Publication");

        jLabel5.setText("Nombre Exemplaires");

        jLabel7.setText("MaisonEdtion");

        jLabel8.setText("categorie");

        jLabel9.setText("nombre de pages");

        jLabel10.setText("edition");

        jLabel6.setText("Positionement");

        lbl_titre_livre.setText("TitreLivre");

        lbl_auteur_livre.setText("AuteurLivre");

        lbl_nb_exemplaire.setText("NbExemplaire");

        lbl_maison_edition.setText("maisonEdition");

        lbl_categorie.setText("categorie");

        lbl_nbPages.setText("nb pages");

        lbl_edition.setText("edition");

        lbl_positionement.setText("positionement");

        btn_MettreLivreAJour.setText("Mettre a jour");
        btn_MettreLivreAJour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_MettreLivreAJourMouseClicked(evt);
            }
        });

        btn_modifierAuteur.setText("modifier");
        btn_modifierAuteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modifierAuteurMouseClicked(evt);
            }
        });

        btn_modifier_nom.setText("modifier");
        btn_modifier_nom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modifier_nomMouseClicked(evt);
            }
        });
        btn_modifier_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_nomActionPerformed(evt);
            }
        });

        btn_modifierNbExemplaire.setText("modifier");
        btn_modifierNbExemplaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modifierNbExemplaireMouseClicked(evt);
            }
        });

        btn_changerMaisonEdition.setText("modifier");
        btn_changerMaisonEdition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_changerMaisonEditionMouseClicked(evt);
            }
        });

        btn_ModiferCategorie.setText("modifier");
        btn_ModiferCategorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ModiferCategorieMouseClicked(evt);
            }
        });
        btn_ModiferCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModiferCategorieActionPerformed(evt);
            }
        });

        btn_ModifierNbPages.setText("modifier");
        btn_ModifierNbPages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ModifierNbPagesMouseClicked(evt);
            }
        });

        btn_ModifierEditionLivre.setText("modifier");
        btn_ModifierEditionLivre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ModifierEditionLivreMouseClicked(evt);
            }
        });

        btn_ModifierPositionement.setText("modifier");
        btn_ModifierPositionement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ModifierPositionementMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Info Ressource");

        btn_retour.setText("retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(147, 147, 147)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_edition, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_positionement, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_MettreLivreAJour)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datechooser_ModifierDatePublication, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_auteur_livre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_nb_exemplaire, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_maison_edition, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_nbPages, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_ModifierNbPages)
                                            .addComponent(btn_ModiferCategorie)
                                            .addComponent(btn_changerMaisonEdition)
                                            .addComponent(btn_modifierNbExemplaire)
                                            .addComponent(btn_modifier_nom)
                                            .addComponent(btn_modifierAuteur)
                                            .addComponent(btn_ModifierEditionLivre)
                                            .addComponent(btn_ModifierPositionement))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(133, 133, 133)
                        .addComponent(lbl_titre_livre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btn_changer_image))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btn_retour)
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_retour))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_titre_livre)
                    .addComponent(jLabel2)
                    .addComponent(btn_modifier_nom))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(datechooser_ModifierDatePublication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_nb_exemplaire)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_modifierNbExemplaire))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(lbl_maison_edition)
                                    .addComponent(btn_changerMaisonEdition)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_auteur_livre)
                                    .addComponent(btn_modifierAuteur))))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_categorie)
                            .addComponent(jLabel8)
                            .addComponent(btn_ModiferCategorie))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nbPages)
                            .addComponent(btn_ModifierNbPages))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_edition)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_ModifierEditionLivre))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbl_positionement)
                            .addComponent(btn_ModifierPositionement)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_changer_image)
                    .addComponent(btn_MettreLivreAJour))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_changer_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_changer_imageMouseClicked
        // TODO add your handling code here:
        
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new ImageFilter());
        fileChooser.setAcceptAllFileFilterUsed(false);
        
        int option = fileChooser.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            
            
            try{
                this.newImageName = file.getName();
                RenderedImage image = ImageIO.read(file);
                ImageIO.write(image,"jpg",new File(path+file.getName()));
                this.lbl_image.setIcon(new ImageIcon(path+file.getName()));
            }catch(IOException e){
                System.out.println(e);
            }
        }else{
             this.lbl_image.setText(" Aucune Image Choisie  ");
        }
        
        
        
    }//GEN-LAST:event_btn_changer_imageMouseClicked

    private void btn_modifier_nomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modifier_nomMouseClicked
        // TODO add your handling code here:
        
        String nouveau_titre = JOptionPane.showInputDialog("Entrez Le nouveau nom du livre");
        if(nouveau_titre != null){
            if(nouveau_titre.length() > 0){
                this.lbl_titre_livre.setText(nouveau_titre);
            }
        }
    }//GEN-LAST:event_btn_modifier_nomMouseClicked

    private void btn_modifierAuteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modifierAuteurMouseClicked
        // TODO add your handling code here:
            String nouvel_auteur = JOptionPane.showInputDialog("Entrez Le nouvel auteur du livre");
            if(nouvel_auteur != null){
                if(nouvel_auteur.length() > 0){
                    this.lbl_auteur_livre.setText(nouvel_auteur);
                }
            }
    }//GEN-LAST:event_btn_modifierAuteurMouseClicked

    private void btn_modifierNbExemplaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modifierNbExemplaireMouseClicked
        // TODO add your handling code here:
            String nouveau_nbExemplaire = JOptionPane.showInputDialog("Entrez Le nouveau nombres d'exemplaires du livre");
            if(nouveau_nbExemplaire != null){
                if(nouveau_nbExemplaire.length() > 0){
                    this.lbl_nb_exemplaire.setText(nouveau_nbExemplaire);
                }
            }
    }//GEN-LAST:event_btn_modifierNbExemplaireMouseClicked

    private void btn_changerMaisonEditionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_changerMaisonEditionMouseClicked
        // TODO add your handling code here:
        String nouvelle_maisonEdition = JOptionPane.showInputDialog("Entrez La nouvelle maison d'edition du livre");
            if(nouvelle_maisonEdition != null){
                if(nouvelle_maisonEdition.length() > 0){
                    this.lbl_maison_edition.setText(nouvelle_maisonEdition);
                }
            }
    }//GEN-LAST:event_btn_changerMaisonEditionMouseClicked

    private void btn_ModiferCategorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModiferCategorieMouseClicked
        // TODO add your handling code here:
          String nouvelle_categorie = JOptionPane.showInputDialog("Entrez La nouvelle categorie du livre");
            if(nouvelle_categorie != null){
                if(nouvelle_categorie.length() > 0){
                    this.lbl_categorie.setText(nouvelle_categorie);
                }
            }
        
    }//GEN-LAST:event_btn_ModiferCategorieMouseClicked

    private void btn_ModifierNbPagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModifierNbPagesMouseClicked
        // TODO add your handling code here:
         String nouveau_nbPages = JOptionPane.showInputDialog("Entrez Le nouveau nombres de pages du livre");
            if(nouveau_nbPages != null){
                if(nouveau_nbPages.length() > 0){
                    this.lbl_nbPages.setText(nouveau_nbPages);
                }
            }
    }//GEN-LAST:event_btn_ModifierNbPagesMouseClicked

    private void btn_ModifierEditionLivreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModifierEditionLivreMouseClicked
        // TODO add your handling code here:
         String nouvelle_edition = JOptionPane.showInputDialog("Entrez La nouvelle edition du livre");
            if(nouvelle_edition != null){
                if(nouvelle_edition.length() > 0){
                    this.lbl_edition.setText(nouvelle_edition);
                }
            }
    }//GEN-LAST:event_btn_ModifierEditionLivreMouseClicked

    private void btn_ModifierPositionementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ModifierPositionementMouseClicked
        // TODO add your handling code here:
          String nouveau_positionement = JOptionPane.showInputDialog("Entrez Le nouveau positionement du livre");
            if(nouveau_positionement != null){
                if(nouveau_positionement.length() > 0){
                    this.lbl_positionement.setText(nouveau_positionement);
                }
            }
    }//GEN-LAST:event_btn_ModifierPositionementMouseClicked

    private void btn_MettreLivreAJourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_MettreLivreAJourMouseClicked
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null,"Voulez vous vraiment mettre ce livre a jour ?");
        if(option==0){
            this.mLivre.auteur = this.lbl_auteur_livre.getText();
            this.mLivre.categorie = this.lbl_categorie.getText();
            this.mLivre.datePublication = this.datechooser_ModifierDatePublication.getDate();
            this.mLivre.edition = this.lbl_edition.getText();
            this.mLivre.maisonEdition = this.lbl_maison_edition.getText();
            this.mLivre.nbExemplaires = Integer.parseInt(this.lbl_nb_exemplaire.getText());
            this.mLivre.positionement = this.lbl_positionement.getText();
            this.mLivre.titre = this.lbl_titre_livre.getText();
            this.mLivre.nomImage = this.newImageName;
            
                
        try{
              java.util.Date d = this.mLivre.datePublication;
           java.sql.Date sqldate = null;
            if (d == null) {
                System.out.println("No date specified!");
            } else {
                sqldate = new java.sql.Date(d.getTime());
                // Do something with sqldate
            }
            
                  Connection con = DBConnect.connect();
                 String insertQuery = "UPDATE livre SET Titre = ?,"
                         + " Auteur = ?,"
                         + " DatePublication = ?,"
                         + " NombreDexemplaires = ?,"
                         + " Positionement = ?,"
                         + "MaisonEdition = ?,"
                         + " Stylecategorie = ?,"
                         + " nbPage = ?,"
                         + " edition = ?,"
                         + "nomImage = ?"
                         + "WHERE Id = ?";
                 
               PreparedStatement requeteInsertion = con.prepareStatement(insertQuery);
                requeteInsertion.setString(1,this.mLivre.titre);
                 requeteInsertion.setString(2,this.mLivre.auteur);
                  requeteInsertion.setDate(3, sqldate);
                  requeteInsertion.setInt(4, this.mLivre.nbExemplaires);
                   requeteInsertion.setString(5,this.mLivre.positionement);
                    requeteInsertion.setString(6,this.mLivre.maisonEdition);
                     requeteInsertion.setString(7,this.mLivre.categorie);
                      requeteInsertion.setInt(8,this.mLivre.nbPages);
                      requeteInsertion.setString(9,this.mLivre.edition);
                      requeteInsertion.setString(10,this.mLivre.nomImage);
                      requeteInsertion.setInt(11, this.mLivre.id);
                      
                requeteInsertion.execute();
                JOptionPane.showMessageDialog(null, "Enregistree avec success");
            
                con.close();
        }catch(Exception e){
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_btn_MettreLivreAJourMouseClicked

    private void btn_ModiferCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModiferCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ModiferCategorieActionPerformed

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed
        // TODO add your handling code here:
       this.mFenetreAcceuil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_retourActionPerformed

    private void btn_modifier_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modifier_nomActionPerformed

    private void btn_changer_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changer_imageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_changer_imageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreModifierLivre(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MettreLivreAJour;
    private javax.swing.JButton btn_ModiferCategorie;
    private javax.swing.JButton btn_ModifierEditionLivre;
    private javax.swing.JButton btn_ModifierNbPages;
    private javax.swing.JButton btn_ModifierPositionement;
    private javax.swing.JButton btn_changerMaisonEdition;
    private javax.swing.JButton btn_changer_image;
    private javax.swing.JButton btn_modifierAuteur;
    private javax.swing.JButton btn_modifierNbExemplaire;
    private javax.swing.JButton btn_modifier_nom;
    private javax.swing.JButton btn_retour;
    private com.toedter.calendar.JDateChooser datechooser_ModifierDatePublication;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_auteur_livre;
    private javax.swing.JLabel lbl_categorie;
    private javax.swing.JLabel lbl_edition;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_maison_edition;
    private javax.swing.JLabel lbl_nbPages;
    private javax.swing.JLabel lbl_nb_exemplaire;
    private javax.swing.JLabel lbl_positionement;
    private javax.swing.JLabel lbl_titre_livre;
    // End of variables declaration//GEN-END:variables
}
