/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import database.DBConnect;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lmsschoolproject.CD;
import lmsschoolproject.PROJECTCONSTANTS;
import utilities.ImageFilter;

/**
 *
 * @author KIBITI Wen Life
 */
public class FenetreModifierCD extends javax.swing.JFrame {
    
    private CD mCD;
    FenetreAcceuil mFenetreAcceuil;

    /**
     * Creates new form FenetreModifierCD
     */
    public FenetreModifierCD(CD cd, FenetreAcceuil acceuil) {
        initComponents();
        this.mCD = cd;
        this.mFenetreAcceuil = acceuil;
        if(cd != null){
        this.lbl_titre.setText(cd.titre);
        this.lbl_auteur.setText(cd.auteur);
        this.lbl_duree.setText(cd.duree.toString());
        this.lbl_maison_edition.setText(cd.maisonEdition);
        this.lbl_nb_Exemplaire.setText(String.valueOf(cd.nbExemplaires));
        this.lbl_positionement.setText(cd.positionement);
        this.lbl_taille.setText(String.valueOf(cd.taille));
        this.txt_date_publication.setDate(cd.datePublication);
        
                BufferedImage img = null;
            try {
                img = ImageIO.read(new File(PROJECTCONSTANTS.IMAGES_PATH+cd.nomImage));
                
                Image dimg = img.getScaledInstance(this.lbl_image.getWidth(),this.lbl_image.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(dimg);
                this.lbl_image.setIcon(imageIcon);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
     protected class GradientJPanel extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g; 
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            
            GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0,0,width,height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new GradientJPanel();
        lbl_image = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_titre = new javax.swing.JLabel();
        lbl_auteur = new javax.swing.JLabel();
        lbl_duree = new javax.swing.JLabel();
        lbl_maison_edition = new javax.swing.JLabel();
        lbl_nb_Exemplaire = new javax.swing.JLabel();
        lbl_taille = new javax.swing.JLabel();
        lbl_positionement = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_date_publication = new com.toedter.calendar.JDateChooser();
        btn_modifier_titre = new javax.swing.JButton();
        btn_modifier_auteur = new javax.swing.JButton();
        btn_modifier_duree = new javax.swing.JButton();
        btn_modifier_maisonEdition = new javax.swing.JButton();
        btn_modifier_nbExemplaire = new javax.swing.JButton();
        btn_modifier_taille = new javax.swing.JButton();
        btn_modifier_positionement = new javax.swing.JButton();
        btn_mettreAJour = new javax.swing.JButton();
        btn_changerImage = new javax.swing.JButton();
        btn_retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_image.setText("jLabel1");

        jLabel2.setText("Titre");

        jLabel3.setText("Auteur");

        jLabel4.setText("Duree");

        jLabel5.setText("MaisonEdition");

        jLabel6.setText("Nombre Exemplaires");

        jLabel7.setText("Taille");

        jLabel8.setText("Positionement");

        lbl_titre.setText("lbl_titre");

        lbl_auteur.setText("lbl_auteur");

        lbl_duree.setText("lbl_duree");

        lbl_maison_edition.setText("jLabel12");

        lbl_nb_Exemplaire.setText("jLabel13");

        lbl_taille.setText("jLabel14");

        lbl_positionement.setText("jLabel15");

        jLabel16.setText("Date Publication");

        btn_modifier_titre.setText("modifier");
        btn_modifier_titre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_titreActionPerformed(evt);
            }
        });

        btn_modifier_auteur.setText("modifier");
        btn_modifier_auteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_auteurActionPerformed(evt);
            }
        });

        btn_modifier_duree.setText("modifier");
        btn_modifier_duree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_dureeActionPerformed(evt);
            }
        });

        btn_modifier_maisonEdition.setText("modifier");
        btn_modifier_maisonEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_maisonEditionActionPerformed(evt);
            }
        });

        btn_modifier_nbExemplaire.setText("modifier");
        btn_modifier_nbExemplaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_nbExemplaireActionPerformed(evt);
            }
        });

        btn_modifier_taille.setText("modifier");
        btn_modifier_taille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_tailleActionPerformed(evt);
            }
        });

        btn_modifier_positionement.setText("modifier");
        btn_modifier_positionement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_positionementActionPerformed(evt);
            }
        });

        btn_mettreAJour.setBackground(new java.awt.Color(153, 255, 0));
        btn_mettreAJour.setText("mettre a jour");
        btn_mettreAJour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mettreAJourActionPerformed(evt);
            }
        });

        btn_changerImage.setText("changer image");
        btn_changerImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changerImageActionPerformed(evt);
            }
        });

        btn_retour.setText("retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btn_changerImage)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_modifier_titre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_auteur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_modifier_maisonEdition)
                                    .addComponent(btn_modifier_auteur)
                                    .addComponent(btn_modifier_duree)
                                    .addComponent(btn_modifier_nbExemplaire)
                                    .addComponent(btn_modifier_taille)
                                    .addComponent(btn_modifier_positionement))))
                        .addGap(104, 104, 104))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_positionement)
                            .addComponent(lbl_taille)
                            .addComponent(lbl_nb_Exemplaire)
                            .addComponent(lbl_maison_edition)
                            .addComponent(txt_date_publication, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_duree))
                        .addGap(196, 196, 196))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(btn_mettreAJour))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btn_retour)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btn_retour)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_titre)
                    .addComponent(btn_modifier_titre))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbl_auteur)
                            .addComponent(btn_modifier_auteur))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lbl_duree)
                            .addComponent(btn_modifier_duree))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_maison_edition)
                            .addComponent(btn_modifier_maisonEdition))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(txt_date_publication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(lbl_nb_Exemplaire)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(btn_modifier_nbExemplaire)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lbl_taille)
                            .addComponent(btn_modifier_taille))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lbl_positionement)
                            .addComponent(btn_modifier_positionement))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(btn_mettreAJour)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_changerImage)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modifier_titreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_titreActionPerformed
        // TODO add your handling code here:
         String nouveau_titre = JOptionPane.showInputDialog("Entrez Le nouveau titre du cd");
        if(nouveau_titre != null){
            if(nouveau_titre.length() > 0){
                this.lbl_titre.setText(nouveau_titre);
            }
        }
    }//GEN-LAST:event_btn_modifier_titreActionPerformed

    private void btn_modifier_auteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_auteurActionPerformed
        // TODO add your handling code here:
          String nouvel_auteur = JOptionPane.showInputDialog("Entrez Le nouvel auteur du cd");
        if(nouvel_auteur != null){
            if(nouvel_auteur.length() > 0){
                this.lbl_auteur.setText(nouvel_auteur);
            }
        }
    }//GEN-LAST:event_btn_modifier_auteurActionPerformed

    private void btn_modifier_dureeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_dureeActionPerformed
        // TODO add your handling code here:
           String nouvelle_duree = JOptionPane.showInputDialog("Entrez La nouvelle duree du cd");
        if(nouvelle_duree != null){
            if(nouvelle_duree.length() > 0){
                this.lbl_duree.setText(nouvelle_duree);
            }
        }
    }//GEN-LAST:event_btn_modifier_dureeActionPerformed

    private void btn_modifier_maisonEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_maisonEditionActionPerformed
        // TODO add your handling code here:
          String nouvelle_maisonEdition = JOptionPane.showInputDialog("Entrez La nouvelle maison edition du cd");
        if(nouvelle_maisonEdition != null){
            if(nouvelle_maisonEdition.length() > 0){
                this.lbl_maison_edition.setText(nouvelle_maisonEdition);
            }
        }
    }//GEN-LAST:event_btn_modifier_maisonEditionActionPerformed

    private void btn_modifier_nbExemplaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_nbExemplaireActionPerformed
        // TODO add your handling code here:
         String nouveau_nombreExemplaire = JOptionPane.showInputDialog("Entrez Le nouveau nombre d'exemplaire du cd");
        if(nouveau_nombreExemplaire != null){
            if(nouveau_nombreExemplaire.length() > 0){
                this.lbl_nb_Exemplaire.setText(nouveau_nombreExemplaire);
            }
        }
    }//GEN-LAST:event_btn_modifier_nbExemplaireActionPerformed

    private void btn_modifier_tailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_tailleActionPerformed
        // TODO add your handling code here:
         String nouvel_taille = JOptionPane.showInputDialog("Entrez Le nouvel taille du cd");
        if(nouvel_taille != null){
            if(nouvel_taille.length() > 0){
                this.lbl_taille.setText(nouvel_taille);
            }
        }
    }//GEN-LAST:event_btn_modifier_tailleActionPerformed

    private void btn_modifier_positionementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_positionementActionPerformed
        // TODO add your handling code here:
        String nouveau_positionement = JOptionPane.showInputDialog("Entrez Le nouveau positionement du cd");
        if(nouveau_positionement != null){
            if(nouveau_positionement.length() > 0){
                this.lbl_positionement.setText(nouveau_positionement);
            }
        }
    }//GEN-LAST:event_btn_modifier_positionementActionPerformed

    private void btn_changerImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changerImageActionPerformed
        // TODO add your handling code here:
         JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new ImageFilter());
        fileChooser.setAcceptAllFileFilterUsed(false);
        
        int option = fileChooser.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            this.lbl_image.setText(file.getName());
            
          
                 BufferedImage img = null;
            try {
                img = ImageIO.read(file);
                 ImageIO.write(img,"jpg",new File(PROJECTCONSTANTS.IMAGES_PATH+file.getName()));
                Image dimg = img.getScaledInstance(this.lbl_image.getWidth(),this.lbl_image.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(dimg);
                this.lbl_image.setIcon(imageIcon);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }else{
             this.lbl_image.setText(" Aucune Image Choisie  ");
        }
    }//GEN-LAST:event_btn_changerImageActionPerformed

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed
        // TODO add your handling code here:
       this.mFenetreAcceuil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_retourActionPerformed

    private void btn_mettreAJourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mettreAJourActionPerformed
        // TODO add your handling code here:
         int option = JOptionPane.showConfirmDialog(null,"Voulez vous vraiment mettre ce livre a jour ?");
        if(option==0){
            this.mCD.auteur = this.lbl_auteur.getText();
            this.mCD.datePublication = this.txt_date_publication.getDate();
            this.mCD.taille = Integer.parseInt(this.lbl_taille.getText());
            String duree = this.lbl_duree.getText();
            this.mCD.maisonEdition = this.lbl_maison_edition.getText();
            this.mCD.nbExemplaires = Integer.parseInt(this.lbl_nb_Exemplaire.getText());
            this.mCD.positionement = this.lbl_positionement.getText();
            this.mCD.titre = this.lbl_titre.getText();
            this.mCD.nomImage = this.lbl_image.getText();
            
                
        try{
              java.util.Date d = this.mCD.datePublication;
           java.sql.Date sqldate = null;
            if (d == null) {
                System.out.println("No date specified!");
            } else {
                sqldate = new java.sql.Date(d.getTime());
                // Do something with sqldate
            }
            
                  Connection con = DBConnect.connect();
                 String insertQuery = "UPDATE cd SET Titre = ?,"
                         + " Auteur = ?,"
                         + " DatePublication = ?,"
                         + " NombreDexemplaires = ?,"
                         + " Positionement = ?,"
                         + "MaisonEdition = ?,"
                         + " duree = ?,"
                         + " taille = ?,"
                         + "nomImage = ?"
                         + "WHERE Id = ?";
                 
               PreparedStatement requeteInsertion = con.prepareStatement(insertQuery);
                requeteInsertion.setString(1,this.mCD.titre);
                 requeteInsertion.setString(2,this.mCD.auteur);
                  requeteInsertion.setDate(3, sqldate);
                  requeteInsertion.setInt(4, this.mCD.nbExemplaires);
                   requeteInsertion.setString(5,this.mCD.positionement);
                    requeteInsertion.setString(6,this.mCD.maisonEdition);
                     requeteInsertion.setString(7,duree);
                      requeteInsertion.setInt(8,this.mCD.taille);
                     
                      requeteInsertion.setString(9,this.mCD.nomImage);
                      requeteInsertion.setInt(10, this.mCD.id);
                      
                requeteInsertion.execute();
                JOptionPane.showMessageDialog(null, "Enregistree avec success");
            
                con.close();
        }catch(Exception e){
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_btn_mettreAJourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreModifierCD(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_changerImage;
    private javax.swing.JButton btn_mettreAJour;
    private javax.swing.JButton btn_modifier_auteur;
    private javax.swing.JButton btn_modifier_duree;
    private javax.swing.JButton btn_modifier_maisonEdition;
    private javax.swing.JButton btn_modifier_nbExemplaire;
    private javax.swing.JButton btn_modifier_positionement;
    private javax.swing.JButton btn_modifier_taille;
    private javax.swing.JButton btn_modifier_titre;
    private javax.swing.JButton btn_retour;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_auteur;
    private javax.swing.JLabel lbl_duree;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_maison_edition;
    private javax.swing.JLabel lbl_nb_Exemplaire;
    private javax.swing.JLabel lbl_positionement;
    private javax.swing.JLabel lbl_taille;
    private javax.swing.JLabel lbl_titre;
    private com.toedter.calendar.JDateChooser txt_date_publication;
    // End of variables declaration//GEN-END:variables
}
