/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import database.DBConnect;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import lmsschoolproject.PROJECTCONSTANTS;
import lmsschoolproject.ResearchMaterial;
import utilities.ImageFilter;

/**
 *
 * @author KIBITI Wen Life
 */
public class FenetreModifierMR extends javax.swing.JFrame {
    
    ResearchMaterial mResearchMateriel;
    FenetreAcceuil mFenetreAcceuil;

    /**
     * Creates new form FenetreModifierMR
     */
    public FenetreModifierMR(ResearchMaterial materielRecherche,FenetreAcceuil acceuil) {
        initComponents();
        if(materielRecherche != null){
        this.mResearchMateriel = materielRecherche;
        this.mFenetreAcceuil = acceuil;
        this.lbl_titre_mdr.setText(materielRecherche.titre);
        this.lbl_auteur_mdr.setText(materielRecherche.auteur);
        this.lbl_MaisonEdition.setText(materielRecherche.maisonEdition);
        this.txt_datePublication.setDate(materielRecherche.datePublication);
        this.lbl_Positionement.setText(materielRecherche.positionement);
        this.lbl_nombreExemplaire.setText(String.valueOf(materielRecherche.nbExemplaires));
        
        this.mFenetreAcceuil.setVisible(false);
             BufferedImage img = null;
            try {
                img = ImageIO.read(new File(PROJECTCONSTANTS.IMAGES_PATH+materielRecherche.nomImage));
                
                Image dimg = img.getScaledInstance(this.lbl_image.getWidth(),this.lbl_image.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(dimg);
                this.lbl_image.setIcon(imageIcon);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new GradientJPanel();
        lbl_image = new javax.swing.JLabel();
        btn_retour = new javax.swing.JButton();
        btn_changer_image = new javax.swing.JButton();
        btn_mettreAjour = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_auteur_mdr = new javax.swing.JLabel();
        lbl_nombreExemplaire = new javax.swing.JLabel();
        lbl_Positionement = new javax.swing.JLabel();
        lbl_MaisonEdition = new javax.swing.JLabel();
        lbl_titre_mdr = new javax.swing.JLabel();
        txt_datePublication = new com.toedter.calendar.JDateChooser();
        btn_modifier_titre = new javax.swing.JButton();
        btn_modifier_auteur = new javax.swing.JButton();
        btn_modifier_nbExemplaire = new javax.swing.JButton();
        btn_Positionement = new javax.swing.JButton();
        btn_modifier_maisonEdition = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_image.setText("jLabel1");

        btn_retour.setText("retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });

        btn_changer_image.setText("changer image");
        btn_changer_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changer_imageActionPerformed(evt);
            }
        });

        btn_mettreAjour.setText("mettre a jour");
        btn_mettreAjour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mettreAjourActionPerformed(evt);
            }
        });

        jLabel2.setText("Titre");

        jLabel3.setText("Auteur");

        jLabel4.setText("Date Publication");

        jLabel5.setText("Nombre Exemplaire");

        jLabel6.setText("Positionement");

        jLabel7.setText("Maison Edition");

        lbl_auteur_mdr.setText("jLabel8");

        lbl_nombreExemplaire.setText("jLabel10");

        lbl_Positionement.setText("jLabel11");

        lbl_MaisonEdition.setText("jLabel12");

        lbl_titre_mdr.setText("jLabel13");

        btn_modifier_titre.setText("modifier");
        btn_modifier_titre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_titreActionPerformed(evt);
            }
        });

        btn_modifier_auteur.setText("modifier");
        btn_modifier_auteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_auteurActionPerformed(evt);
            }
        });

        btn_modifier_nbExemplaire.setText("modifier");
        btn_modifier_nbExemplaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_nbExemplaireActionPerformed(evt);
            }
        });

        btn_Positionement.setText("modifier");
        btn_Positionement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PositionementActionPerformed(evt);
            }
        });

        btn_modifier_maisonEdition.setText("modifier");
        btn_modifier_maisonEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_maisonEditionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btn_retour))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btn_changer_image)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 442, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_mettreAjour)
                        .addGap(438, 438, 438))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(183, 183, 183))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(86, 86, 86)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_titre_mdr))
                            .addComponent(lbl_auteur_mdr)
                            .addComponent(lbl_nombreExemplaire)
                            .addComponent(lbl_Positionement)
                            .addComponent(lbl_MaisonEdition)
                            .addComponent(txt_datePublication, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_modifier_auteur)
                            .addComponent(btn_modifier_titre)
                            .addComponent(btn_modifier_nbExemplaire)
                            .addComponent(btn_Positionement)
                            .addComponent(btn_modifier_maisonEdition))
                        .addGap(59, 59, 59))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_retour)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(lbl_titre_mdr)
                    .addComponent(btn_modifier_titre))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbl_auteur_mdr)
                            .addComponent(btn_modifier_auteur))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txt_datePublication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_nombreExemplaire)
                            .addComponent(btn_modifier_nbExemplaire))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbl_Positionement)
                            .addComponent(btn_Positionement))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lbl_MaisonEdition)
                            .addComponent(btn_modifier_maisonEdition))))
                .addGap(40, 40, 40)
                .addComponent(btn_changer_image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btn_mettreAjour)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_changer_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changer_imageActionPerformed
        // TODO add your handling code here:
       JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new ImageFilter());
        fileChooser.setAcceptAllFileFilterUsed(false);
        
        int option = fileChooser.showOpenDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            this.lbl_image.setText(file.getName());
            
          
                 BufferedImage img = null;
            try {
                img = ImageIO.read(file);
                 ImageIO.write(img,"jpg",new File(PROJECTCONSTANTS.IMAGES_PATH+file.getName()));
                Image dimg = img.getScaledInstance(this.lbl_image.getWidth(),this.lbl_image.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon imageIcon = new ImageIcon(dimg);
                this.lbl_image.setIcon(imageIcon);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }else{
             this.lbl_image.setText(" Aucune Image Choisie  ");
        }
    }//GEN-LAST:event_btn_changer_imageActionPerformed

    private void btn_modifier_titreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_titreActionPerformed
        // TODO add your handling code here:
         String nouveau_titre = JOptionPane.showInputDialog("Entrez Le nouveau titre du MDR");
        if(nouveau_titre != null){
            if(nouveau_titre.length() > 0){
                this.lbl_titre_mdr.setText(nouveau_titre);
            }
        }
    }//GEN-LAST:event_btn_modifier_titreActionPerformed

    private void btn_modifier_auteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_auteurActionPerformed
        // TODO add your handling code here:
          String nouvel_auteur = JOptionPane.showInputDialog("Entrez Le nouvel auteur du MDR");
        if(nouvel_auteur != null){
            if(nouvel_auteur.length() > 0){
                this.lbl_auteur_mdr.setText(nouvel_auteur);
            }
        }
    }//GEN-LAST:event_btn_modifier_auteurActionPerformed

    private void btn_modifier_nbExemplaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_nbExemplaireActionPerformed
        // TODO add your handling code here:
        String nouveau_nbExemplaire = JOptionPane.showInputDialog("Entrez Le nouveau nombre d'exemplaire du MDR");
        if(nouveau_nbExemplaire != null){
            if(nouveau_nbExemplaire.length() > 0){
                this.lbl_nombreExemplaire.setText(nouveau_nbExemplaire);
            }
        }
    }//GEN-LAST:event_btn_modifier_nbExemplaireActionPerformed

    private void btn_PositionementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PositionementActionPerformed
        // TODO add your handling code here:
        String nouveau_positionement = JOptionPane.showInputDialog("Entrez Le nouveau positionement du MDR");
        if(nouveau_positionement != null){
            if(nouveau_positionement.length() > 0){
                this.lbl_Positionement.setText(nouveau_positionement);
            }
        }
    }//GEN-LAST:event_btn_PositionementActionPerformed

    private void btn_modifier_maisonEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_maisonEditionActionPerformed
        // TODO add your handling code here:
          String nouvelle_maisonEdition = JOptionPane.showInputDialog("Entrer la nouvelle maison d'edition du MDR");
        if(nouvelle_maisonEdition != null){
            if(nouvelle_maisonEdition.length() > 0){
                this.lbl_Positionement.setText(nouvelle_maisonEdition);
            }
        }
    }//GEN-LAST:event_btn_modifier_maisonEditionActionPerformed

    private void btn_mettreAjourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mettreAjourActionPerformed
        // TODO add your handling code here:
            int option = JOptionPane.showConfirmDialog(null,"Voulez vous vraiment mettre ce livre a jour ?");
        if(option==0){
            this.mResearchMateriel.auteur = this.lbl_auteur_mdr.getText();
            this.mResearchMateriel.datePublication = this.txt_datePublication.getDate();
            this.mResearchMateriel.maisonEdition = this.lbl_MaisonEdition.getText();
            this.mResearchMateriel.nbExemplaires = Integer.parseInt(this.lbl_nombreExemplaire.getText());
            this.mResearchMateriel.positionement = this.lbl_Positionement.getText();
            this.mResearchMateriel.titre = this.lbl_titre_mdr.getText();
            this.mResearchMateriel.nomImage = this.lbl_image.getText();
            
                
        try{
              java.util.Date d = this.mResearchMateriel.datePublication;
           java.sql.Date sqldate = null;
            if (d == null) {
                System.out.println("No date specified!");
            } else {
                sqldate = new java.sql.Date(d.getTime());
                // Do something with sqldate
            }
            
                  Connection con = DBConnect.connect();
                 String insertQuery = "UPDATE rsd SET Titre = ?,"
                         + " Auteur = ?,"
                         + " DatePublication = ?,"
                         + " NombreDexemplaires = ?,"
                         + " Positionement = ?,"
                         + "MaisonEdition = ?,"
                         + "nomImage = ?"
                         + "WHERE Id = ?";
                 
               PreparedStatement requeteInsertion = con.prepareStatement(insertQuery);
                requeteInsertion.setString(1,this.mResearchMateriel.titre);
                 requeteInsertion.setString(2,this.mResearchMateriel.auteur);
                  requeteInsertion.setDate(3, sqldate);
                  requeteInsertion.setInt(4, this.mResearchMateriel.nbExemplaires);
                   requeteInsertion.setString(5,this.mResearchMateriel.positionement);
                    requeteInsertion.setString(6,this.mResearchMateriel.maisonEdition);
                   
                     
                      requeteInsertion.setString(7,this.mResearchMateriel.nomImage);
                      requeteInsertion.setInt(8, this.mResearchMateriel.id);
                      
                requeteInsertion.execute();
                JOptionPane.showMessageDialog(null, "Enregistree avec success");
            
                con.close();
        }catch(Exception e){
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_btn_mettreAjourActionPerformed

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed
        // TODO add your handling code here:
       this.mFenetreAcceuil.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_retourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreModifierMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreModifierMR(null,null).setVisible(true);
            }
        });
    }
     protected class GradientJPanel extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g; 
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            
            GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0,0,width,height);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Positionement;
    private javax.swing.JButton btn_changer_image;
    private javax.swing.JButton btn_mettreAjour;
    private javax.swing.JButton btn_modifier_auteur;
    private javax.swing.JButton btn_modifier_maisonEdition;
    private javax.swing.JButton btn_modifier_nbExemplaire;
    private javax.swing.JButton btn_modifier_titre;
    private javax.swing.JButton btn_retour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_MaisonEdition;
    private javax.swing.JLabel lbl_Positionement;
    private javax.swing.JLabel lbl_auteur_mdr;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_nombreExemplaire;
    private javax.swing.JLabel lbl_titre_mdr;
    private com.toedter.calendar.JDateChooser txt_datePublication;
    // End of variables declaration//GEN-END:variables
}
