/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface1;

import database.DBConnect;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.JFrame;
import lmsschoolproject.LoginController;

/**
 *
 * @author KIBITI Wen Life
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
    private void handleLogin(){
          String identifiant = champ_identifiant.getText();
          char[] mdp = champ_mot_de_passe.getPassword();
          String motdepasse = String.valueOf(mdp);
                
        boolean loginStatus = LoginController.loginAdmin(identifiant,motdepasse);
        if(loginStatus){
             allerFenetreAcceuil();
        }else{
            JOptionPane.showMessageDialog(rootPane,"Mot de passe ou Identifiant Incorrecte");
        }
    }
    protected class GradientJPanel extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g; 
            int width = getWidth();
            int height = getHeight();
            
            Color color1 = new Color(52,143,80);
            Color color2 = new Color(86,180,211);
            
            GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
            g2d.setPaint(gp);
            g2d.fillRect(0,0,width,height);
        }
    }
    
    private void allerFenetreAcceuil(){
         FenetreAcceuil acceuil = new FenetreAcceuil();
         acceuil.setVisible(true);
         this.setVisible(false);
         this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        champ_identifiant = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        champ_mot_de_passe = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        bouton_connexion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(0, 255, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 8)); // NOI18N
        jLabel13.setText("<html>\n<body>\n<p>ESIGN LMS est un logiciel conçu dans le but de pouvoir gérer</p>\n<p>la bibliothèque de l'ESIGN-UIECC disposant de divers outils.</p>\n<center>Version d'évaluation.</center>\n</body>\n</html>");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 30));

        jLabel11.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("<html>\n<body>\n<p>Avant de poursuivre,</p>\n<p>veuillez vous</p>\n</body>\n</html>");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 190, 340, 70));

        jLabel12.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(14, 151, 72));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("connecter");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/esign-lms.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("-");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 10, 30));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("X");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, 20, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 220, 10));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 220, 10));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom d'utilisateur");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        champ_identifiant.setBackground(new java.awt.Color(14, 151, 72));
        champ_identifiant.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        champ_identifiant.setForeground(new java.awt.Color(255, 255, 255));
        champ_identifiant.setText("username");
        champ_identifiant.setBorder(null);
        champ_identifiant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                champ_identifiantFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                champ_identifiantFocusLost(evt);
            }
        });
        champ_identifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champ_identifiantActionPerformed(evt);
            }
        });
        jPanel2.add(champ_identifiant, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 218, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mot De Passe");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        champ_mot_de_passe.setBackground(new java.awt.Color(14, 151, 72));
        champ_mot_de_passe.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        champ_mot_de_passe.setForeground(new java.awt.Color(255, 255, 255));
        champ_mot_de_passe.setText("password");
        champ_mot_de_passe.setBorder(null);
        champ_mot_de_passe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                champ_mot_de_passeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                champ_mot_de_passeFocusLost(evt);
            }
        });
        champ_mot_de_passe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                champ_mot_de_passeActionPerformed(evt);
            }
        });
        jPanel2.add(champ_mot_de_passe, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 218, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/connexion-form.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, 240));

        bouton_connexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new.png"))); // NOI18N
        bouton_connexion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bouton_connexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouton_connexionMouseClicked(evt);
            }
        });
        jPanel2.add(bouton_connexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rendu.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void champ_identifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champ_identifiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champ_identifiantActionPerformed

    private void champ_mot_de_passeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_champ_mot_de_passeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_champ_mot_de_passeActionPerformed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel9MousePressed

    private void champ_identifiantFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_champ_identifiantFocusGained
        // TODO add your handling code here:
         if (champ_identifiant.getText().trim().toLowerCase().equals("username")) {
            champ_identifiant.setText("");
         }
    }//GEN-LAST:event_champ_identifiantFocusGained

    private void champ_identifiantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_champ_identifiantFocusLost
            if (champ_identifiant.getText().trim().equals("") || champ_identifiant.getText().trim().toLowerCase().equals("username")) {
            champ_identifiant.setText("username"); 
            }
    }//GEN-LAST:event_champ_identifiantFocusLost

    private void champ_mot_de_passeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_champ_mot_de_passeFocusLost
        // TODO add your handling code here:
         String pass = String.valueOf(champ_mot_de_passe.getPassword());
        if (pass.trim().equals("") || pass.trim().toLowerCase().equals("password")) {
            champ_mot_de_passe.setText("password");
          
        }
       
    }//GEN-LAST:event_champ_mot_de_passeFocusLost

    private void champ_mot_de_passeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_champ_mot_de_passeFocusGained
        // TODO add your handling code here:
         String pass = String.valueOf(champ_mot_de_passe.getPassword());
        if (pass.trim().toLowerCase().equals("password")) {
            champ_mot_de_passe.setText("");
        }
    }//GEN-LAST:event_champ_mot_de_passeFocusGained

    private void bouton_connexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouton_connexionMouseClicked
        // TODO add your handling code here:
        handleLogin();
    }//GEN-LAST:event_bouton_connexionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bouton_connexion;
    private javax.swing.JTextField champ_identifiant;
    private javax.swing.JPasswordField champ_mot_de_passe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
